### ISSUE TITLE
salljobs

### ISSUE THREAD

**Issue by wresch** [giovtorres/slurmtools#2]
Hi Giovanni,

currently salljobs gives the per-job CPU for pending array jobs:

```
$ salljobs -u $SOMEUSER

                           RUNNING/USED     PENDING/REQUESTED
                      -----------------     -----------------
            USERNAME   CPUS NODES  JOBS      CPUS NODES  JOBS
              skobes    610    27   305         1     1   468

$ squeue -t PD -u $SOMEUSER

           JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
31180452_[0-467]      norm    swarm   skobes PD       0:00      1 (Priority)

```
To me it would be more intuitive if it only showed CPUs and JOBS for pending and it showed the
total number of CPUs requested (as it does for individual jobs).

I can try to have a look at the code and submit a pull request if you're not going to have time.

Wolfgang

**Comment by giovtorres** [comment]
sure, go for it!

**Comment by giovtorres** [comment]
Thanks @wresch. This looks good.
